"""Risk and regression classification for AVERA."""

from .confidence import (
    ALL_CONFIDENCE_LEVELS,
    HIGH as HIGH_CONFIDENCE,
    LOW as LOW_CONFIDENCE,
    MEDIUM as MEDIUM_CONFIDENCE,
    confidence_rank,
    normalize_confidence,
    score_confidence,
)
from .evidence import (
    ALL_EVIDENCE_TYPES,
    DEFAULT_MATERIAL_PERCENT_DELTA,
    ENVIRONMENT_EVIDENCE_PATTERNS,
    ENVIRONMENT_FAILURE_REASONS,
    ENVIRONMENT_SIGNAL,
    ENVIRONMENT_STATUS_PATTERNS,
    MATERIAL_WORSENING,
    ThresholdEvidence,
    current_threshold_failures,
    environment_failure_reason,
    environment_failure_signals,
    has_environment_failure_signal,
    has_introduced_threshold_failure,
    has_material_worsening,
    introduced_threshold_failures,
    is_material_worsening,
    material_worsenings,
)
from .risk_levels import (
    ALL_RISK_LEVELS,
    HIGH as HIGH_RISK,
    LOW as LOW_RISK,
    MEDIUM as MEDIUM_RISK,
    RELEASE_BLOCKING,
    SAFETY_CRITICAL,
    normalize_risk_level,
    risk_rank,
    safety_rank,
)
from .risk_classifier import RiskAssessment, classify_risk
from .verdicts import (
    ALL_VERDICTS,
    CONFIRMED_REGRESSION,
    ENVIRONMENT_FAILURE,
    EXPECTED_CHANGE,
    INSUFFICIENT_EVIDENCE,
    POSSIBLE_REGRESSION,
    PREEXISTING_FAILURE,
    REQUIREMENTS_COVERAGE_GAP,
    SUCCESSFUL_CHANGE,
    WORSENED_PREEXISTING_FAILURE,
    is_fault_verdict,
    normalize_verdict,
)

__all__ = [
    "ALL_CONFIDENCE_LEVELS",
    "ALL_EVIDENCE_TYPES",
    "ALL_RISK_LEVELS",
    "ALL_VERDICTS",
    "CONFIRMED_REGRESSION",
    "DEFAULT_MATERIAL_PERCENT_DELTA",
    "ENVIRONMENT_EVIDENCE_PATTERNS",
    "ENVIRONMENT_FAILURE",
    "ENVIRONMENT_FAILURE_REASONS",
    "ENVIRONMENT_SIGNAL",
    "ENVIRONMENT_STATUS_PATTERNS",
    "EXPECTED_CHANGE",
    "HIGH_CONFIDENCE",
    "HIGH_RISK",
    "INSUFFICIENT_EVIDENCE",
    "LOW_CONFIDENCE",
    "LOW_RISK",
    "MATERIAL_WORSENING",
    "MEDIUM_CONFIDENCE",
    "MEDIUM_RISK",
    "POSSIBLE_REGRESSION",
    "PREEXISTING_FAILURE",
    "RELEASE_BLOCKING",
    "REQUIREMENTS_COVERAGE_GAP",
    "RiskAssessment",
    "SAFETY_CRITICAL",
    "SUCCESSFUL_CHANGE",
    "ThresholdEvidence",
    "WORSENED_PREEXISTING_FAILURE",
    "classify_risk",
    "confidence_rank",
    "current_threshold_failures",
    "environment_failure_reason",
    "environment_failure_signals",
    "has_environment_failure_signal",
    "has_introduced_threshold_failure",
    "has_material_worsening",
    "introduced_threshold_failures",
    "is_material_worsening",
    "is_fault_verdict",
    "material_worsenings",
    "normalize_confidence",
    "normalize_risk_level",
    "normalize_verdict",
    "risk_rank",
    "safety_rank",
    "score_confidence",
]
